default: 
	@rm -rf build/;	
	@mkdir build/;
	
	@cp src/index.html build/index.html;
	@cp src/styles.css build/styles.css;
	
	@cat src/js/config.js\
		 src/js/model.js\
		 src/js/view.js\
		 src/js/controller.js\
		 src/js/app.js\
		 > build/scripts.js;	 

